### ISSUE TITLE
Progress bars do not render nicely on iPhone Slack Client

### ISSUE THREAD

**Issue by JosephRedfern** [ikornaselur/similarium#36] opened 2022-05-12 09:51 UTC
![image](https://user-images.githubusercontent.com/861949/168043524-b3e38fa7-072b-4eb4-8530-093279dd17ea.png)

As per screenshot -- progress bars render with gaps under the Slack iOS client.

**Comment by ikornaselur** [comment] 2022-05-12 09:52
Ooh boy, that's worse than I thought!

**Comment by ikornaselur** [comment] 2022-05-17 22:28
Upon investigation, it does seem that this is simply a iOS Slack bug that has to do with rendering of repeated custom emojis. For context, showing multiple 😄 emojis in a row (without any spaces) does work, but showing a custom emoji of dusty stick does not.

I hope that Slack will fix it themselves (I'll have a look at reporting this bug), but the issue may also be worked around if I ever find a good consistent way of implementing #23

Below are screenshots of different platforms I can check with (all native clients)

## On Macos
<img width="262" alt="image" src="https://user-images.githubusercontent.com/3537289/168922015-1be0144d-0c6a-4df1-886a-6c274897f872.png">

## On iOS
<img width="313" alt="image" src="https://user-images.githubusercontent.com/3537289/168922061-ef0861b0-45b1-4be2-9300-d43f234ca386.png">

## On Android
![image](https://user-images.githubusercontent.com/3537289/168922253-7d0b3d7f-2870-4a69-a650-3b0884a0c721.png)

## On Ubuntu
![image](https://user-images.githubusercontent.com/3537289/168922275-e572d35e-9c7d-48e6-bfa9-54f977338228.png)

Closing as `invalid` for now, as it's not a bug with Similarium per se, but rather the Slack client on iOS

**Closed by ikornaselur** 2022-05-17 22:28 UTC
Labels: bug, P-3-high, mobile

**Comment by ikornaselur** [comment] 2022-05-17 22:35
I've reported the bug to Slack directly.

**Comment by ikornaselur** [comment] 2022-05-18 08:14
I've just got a reply from Slack support, acknowledging the bug and that a fix is already in progress 💃
